### PR TITLE
Adding CMAKE api to trigger hipify

### PR DESCRIPTION
**Pull request by pruthvistony**

### CODE REVIEW

**Comment by pruthvistony** [comment]
@micmelesse,
Please review this PR, especially regarding the CONFIG_FILE parameter to hipify interface.

**Review by micmelesse — APPROVED** [review]
LGTM. @pruthvistony  Has this api been tested or integrated by any of our projects yet.

**Comment by pruthvistony** [comment]
> LGTM. @pruthvistony Has this api been tested or integrated by any of our projects yet.

@micmelesse, except the changes related to CONFIG_FILE parameter it is tested on tensorpipe codebase.

**Review by jithunnair-amd — APPROVED** [review]
LGTM. @micmelesse Once this PR is merged, please work on adding the config file support using Triton as a use-case.

**Pull request merged**
